### ISSUE TITLE
Lost connection to host or Steam network

### ISSUE THREAD

**Issue by SuiSidee** [SmartlyDressedGames/Unturned-Docs#108]
So I created a server using U3DS and if I want to connect to a it, it loads for a while and then kicks me out with the text in the title. If I try to connect via "Connect" tab instead, it says "Failed to find a server". I tried everything from disabling firewall to resetting ipconfig but nothing really helps.

**Comment by SDGNelson** [comment]
From your description it sounds like you are connecting over the internet, not LAN, is that correct? In that case you will need to forward the ports 27015 and 27016. https://github.com/SmartlyDressedGames/U3-Docs/blob/master/PortForwarding.md

**Comment by SuiSidee** [comment]
No, I'm trying to connect through the "LAN" tab, my server doesn't show up in the "Internet" tab.

**Comment by SDGNelson** [comment]
And you are sure you are on the same LAN? i.e., you are hosting the server on your home network?

If you can attach the Server_ (id) .log file from the U3DS/Logs folder there might be some more detailed error info.

**Comment by SuiSidee** [comment]
Yes, I'm hosting it on my computer and trying to enter on the same one. Here I attached the file
[Server_Default.log](https://github.com/SmartlyDressedGames/U3-Docs/files/7694966/Server_Default.log)
.

**Comment by SDGNelson** [comment]
It looks like it is booting up okay. Which address/port are you trying to direct connect to? It *should* work if you enter "localhost" without quotes in the IP box and 27015 in the port box.

**Comment by SuiSidee** [comment]
Yeah I'm typing exactly these values, but it shows that it "Failed to connect to a server"

**Comment by SDGNelson** [comment]
That is bizarre... could you attach your Client.log file from the Unturned/Logs folder as well please? The only thing that comes to mind is firewall blocking it, but you mentioned disabling the firewall. On first install the dedicated server might have done a Windows popup saying "allow Unturned.exe to something something network", maybe existing block there applies regardless of disabling firewall?

**Comment by SuiSidee** [comment]
I've checked the incoming rules of firewall and all of the Unturned ones are fine. Here's the file
[Client.log](https://github.com/SmartlyDressedGames/U3-Docs/files/7695051/Client.log)
.

**Comment by SDGNelson** [comment]
It looks like it loaded the server lobby screen and that was the last thing mentioned. You clicked Connect and then it failed to join?

**Comment by SuiSidee** [comment]
Yeah exactly. When I click Connect, it shows me Loading screen, but the Loading bar isn't moving at all and it drops me out after a while with "Lost connection to host or Steam network:.

**Comment by SDGNelson** [comment]
It sounds like this might be a deeper issue with Steam networking itself since there are no game errors. Today is a little hectic so I have not tested this command-line option recently, but if you can add "-LogSteamNetworkingSockets=6" without quotes to your Steam > Unturned > Launch Options and then try connecting again there might be more detailed connection loss info in your Client.log file.

**Comment by SuiSidee** [comment]
[Client.log](https://github.com/SmartlyDressedGames/U3-Docs/files/7695225/Client.log)

**Comment by SDGNelson** [comment]
So the relevant section is:

[2021-12-10 21:14:16] Client set SNS debug output detail level to k_ESteamNetworkingSocketsDebugOutputType_Verbose
[2021-12-10 21:14:16] Client Steam Networking available
[2021-12-10 21:14:16] Client connecting to 192.168.0.150:27016
[2021-12-10 21:14:16] [#447306291 UDP invalid@192.168.0.150:27016] Our cert expires in 50358 seconds.
[2021-12-10 21:14:26] Client connection problem detected locally (5003) "Timed out attempting to connect"
[2021-12-10 21:14:26] Client transport failure: Lost connection to host or Steam network.

Nothing jumps out at me as unusual there. Sorry to keep asking for more and more files, but it might be worth adding -LogSteamNetworkingSockets=6 before +LanServer in your server launch script, and then we might get something interesting from the server log again after you try connecting. For example maybe it will log that it ignored the connection request for some reason, or maybe it will have a different address than 192.168.0.150:27016.

**Comment by SuiSidee** [comment]
Actually I don't have a script to launch the server, I'm launching it through Steam using U3DS, so should i put these into U3DS launch options?

**Comment by SuiSidee** [comment]
Anyway, thank you for trying to help and spending your time here, maybe I'll somehow figure it out.

**Comment by SDGNelson** [comment]
Are you launching it through your Steam library? Here is the documentation on creating a launch script: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md#how-to-launch-server-on-windows

**Comment by Trecopalyps** [comment]
Hi Nelson!
I´m having exactly the same issue described above:

- Hosting on the same computer im trying to join from
- Server boots up with no errors
- Server shows up in LAN tab
- Error: Lost connection to host or Steam network
- Im hosting the server via launch script exactly as explained in the documentation

I added -LogSteamNetworkingSockets=6 to my launch script as you asked for above.

`"%~dp0ServerHelper.bat" -LogSteamNetworkingSockets=6 +LanServer/WomServer`

Now the server crashes. Here is the log file:

[Server_WomServer.log](https://github.com/SmartlyDressedGames/U3-Docs/files/7892144/Server_WomServer.log)

If i can provide you with more files to fix this im eager to help!

**Comment by SDGNelson** [comment]
@Trecopalyps sorry for the trouble! Thanks for the log. It looks like you are running into a recent mysterious issue which is on my to-fix list for this Friday. For some reason an extra zero is showing up in the steam_appid.txt file for some hosts. If you look for steam_appid.txt in your U3DS folder and change it to 304930 does it work properly?

**Comment by Trecopalyps** [comment]
Yes! That fixed it :)
