### ISSUE TITLE
U3DS Bug/Error - Assertion Failed: SteamnetworkingSockets service thread waited (some number)ms for lock!

### ISSUE THREAD

**Issue by GabrielMaestre** [SmartlyDressedGames/Unturned-Docs#114]
Hello again friend, this is the first time I see this Bug/Error.
I've created a few servers before and it never occurred to me. If you need more information, just say :D

------------------------------------------

Spec.:

- Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1058-oracle x86_64)
- CPU:
-           product: AMD EPYC 7551 32-Core Processor
-           vendor: Advanced Micro Devices [AMD]
-           width: 64 bits
- 8GB RAM

_Requisites Commands >
 sudo add-apt-repository multiverse;
 sudo dpkg --add-architecture i386;
 sudo apt update;
 sudo apt install lib32gcc1 steamcmd;_
 
------------------------------------------
 

>  src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1852) : Assertion Failed: SteamnetworkingSockets service thread waited 98ms for lock!  This directly adds to network latency!  It could be a bug, but it's usually caused by general performance problem such as thread starvation or a debug output handler taking too long. (This Error repeats Infinity in VPS, and consumes 80%+ CPU, and some RAM).

------------------------------------------
 

[Server_odt-train.log](https://github.com/SmartlyDressedGames/U3-Docs/files/7704173/Server_odt-train.log)
[Server_odt-train_Prev.log](https://github.com/SmartlyDressedGames/U3-Docs/files/7704174/Server_odt-train_Prev.log)

**Comment by SDGNelson** [comment]
Sorry it looks like the logs end at "Requesting cert" so there might be an error happening later, but this warning is saying that the server is running at less than 11 frames per second.

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
