### ISSUE TITLE
unable to find the server IP

### ISSUE THREAD

**Issue by Nyxiia21** [SmartlyDressedGames/Unturned-Docs#119]
hey, it seems like i can't find the server IP. I have searched everywhere and in every file, i followed the steps etc tho nothing

**Comment by SDGNelson** [comment]
Sorry can you elaborate on what you mean by that please? If you are hosting your own server on your home network then the server's public IP would be the one that comes up when you google "what is my ip".

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
