### ISSUE TITLE
When others join my server....

### ISSUE THREAD

**Issue by NotH1ard** [SmartlyDressedGames/Unturned-Docs#142]
Hello
I've been having an issue that when some one try's to join my server it says lost connection to host or steam network. My server is port forwarded and when you try to connect it shows the servers name but when they press join after a bit is say lost connection to host or steam network. Any fixes?

Thanks for help

**Comment by NotH1ard** [comment]
[Server_MyServer.log](https://github.com/SmartlyDressedGames/U3-Docs/files/8163402/Server_MyServer.log)
  No client.log

**Comment by NotH1ard** [comment]
[Client.log](https://github.com/SmartlyDressedGames/U3-Docs/files/8163480/Client.log)
found it. But the error dosen't show for me but for other people that try to join

**Comment by SDGNelson** [comment]
Fortunately (or perhaps unfortunately) no errors on the server side, but I would recommend setting GSLT so that it shows in server list: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/GameServerLoginTokens.md

So this Client.log is from your connecting? If you can connect over your LAN, but your friends cannot connect, then my guess is perhaps a port forwarding issue?

**Comment by NotH1ard** [comment]
yes possibly could be it but when I go on unturned-servers.net it say all is okay when I put in ip and port that it should work but when some one else except me try to join it shows lost connection to the host or steam network.

**Comment by CyberAndrii** [comment]
From docs:
```
Each Unturned server uses two consecutive ports while running. The first is for server list queries, and the second for in-game traffic.
```

From what you said I may guess that the first port is forwarded but the second is not.

**Comment by NotH1ard** [comment]
![image](https://user-images.githubusercontent.com/69733624/156538452-e0332fa7-ec4a-491b-80ab-fbba7ab6b974.png)
CyberAndri. The 2 ports 27015 and 27016 are portforwarded/port mapped but mybe I have some thing wrong with my settings you can see in attachment. If  I have any errors tell me how to fix it

**Comment by SDGNelson** [comment]
I am inclined to agree with @CyberAndrii (thanks!) that perhaps the query port used by the server list and lobby screen is forwarded, but not the game traffic port. From your screenshot it looks fine however... Do you have the documentation for your port forwarding settings? Perhaps the "external source port number" requires the client port to be within that range? (if so, disable)

Also, it is a small chance, but if you can get the Client.log from a friend outside your LAN after trying to join your server there *might* be something.

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
