### ISSUE TITLE
Set health field to public for Zombie and Animal types

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-Docs#143]

**Comment by Sl4vP0weR** [comment]
Or create Health property with ushort type instead of GetHealth method

**Comment by SDGNelson** [comment]
Sorry, I have been overly cautious about which newer code is in the public API. This seems quite reasonable though - will do.

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
