### ISSUE TITLE
please help in the game unturned (lost connection to host or steam network)

### ISSUE THREAD

**Issue by SpaisFox** [SmartlyDressedGames/Unturned-Docs#172]
Hello, I've been playing a game like Unturned for a while now, but I got an error after the last update. namely, I play somewhere for 1-2 minutes and I crash and write an error ====lost connection to host or steam network.====
I've already looked at a lot of guides on YouTube and nothing helped. your last hope. I hope for a quick answer thanks.

**Comment by SDGNelson** [comment]
Sorry, unfortunately this is mostly outside the control of the game. Perhaps the connection to Steam is blocked? If you can send me this file after it happens I can take a look, but most likely it is a generic lost connection error:
1. Right-click Unturned in your Steam Library
2. Select Properties... > Local Files > Browse...
3. Open the Logs folder
4. Attach the Client.log file

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
