### ISSUE TITLE
floating the items

### ISSUE THREAD

**Issue by Bar0nline** [SmartlyDressedGames/Unturned-Docs#174]
**Is there a way to make items float on the sea?**
![image](https://user-images.githubusercontent.com/80773683/182878665-8d60cc9b-f16b-44b4-a985-4418a4f0e9c2.png)

**Comment by Bar0nline** [comment]
Doesn't anyone know?

**Comment by Bar0nline** [comment]
No idea?

**Comment by MoltonMontro** [comment]
No such official modding feature/support currently exists for that, no.

If you'd like to suggest a new feature for the game (or for use by modders), consider making a new post on one of our official communities. For example, on [our forums](https://forum.smartlydressedgames.com/c/unturned/u3-discussion/6).

**Comment by Ongjming** [comment]
I kinda make that happen by using it as a placeable barricade, while within Unity adding this: https://github.com/olie304/UnturnedScripts/blob/master/Buoyancy.cs to the gameobject. The barricade would float on water, though like those barrels in the picture or real life float board, it is not very stable (It wobbles).

**Comment by Bar0nline** [comment]
Thanks, a comment worth trying :3

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
