### ISSUE TITLE
Empty sky with OpenGL

### ISSUE THREAD

**Issue by awesqm** [SmartlyDressedGames/Unturned-Docs#175]
privet
screenshot with `-force-vulkan`
![yes clouds](https://user-images.githubusercontent.com/55652142/184007775-1d19c373-6196-4972-8b1f-86c72052217f.png)

screenshot without launch options (opengl)
![where clouds bro](https://user-images.githubusercontent.com/55652142/184007989-5c22a6d1-9134-47b1-9031-f03f66b8bd64.png)
screenshots were taken on a preview branch, but it's the same for production branch.

also, the "input lag?" issue is still there (https://github.com/SmartlyDressedGames/U3-Docs/issues/153) even though unity was updated to 2020.something. Camera movement just feels weird on vulkan.

**Comment by 0wM** [comment]
i just limited my fps and camera movement is identical to opengl now

**Comment by MoltonMontro** [comment]
Hey, 0wM.

Sorry for the slow response, but this is a known issue. Note that this repository is for modding documentation. In the future, please post bug reports in one of our more suitable locations. E.g., on the [3.x Community repo](https://github.com/SmartlyDressedGames/Unturned-3.x-Community), or somewhere like on our [official forums](https://forum.smartlydressedgames.com/c/unturned/u3-support/32).

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
