### ISSUE TITLE
não consigo atualizar o server alguem pode me ajuda?

### ISSUE THREAD

**Issue by Chaosran** [SmartlyDressedGames/Unturned-Docs#189]
eu coloco o comando pra atualizar mas aparece unable to match  with any built-in commands

**Comment by SDGNelson** [comment]
It sounds like you might be running the app_update command in the dedicated server terminal. To update the server you need to run that command in steamcmd, similar to how you first installed the server.

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
