### ISSUE TITLE
Road nodes with "Ignore Terrain"

### ISSUE THREAD

**Issue by ToothyDeerryte** [SmartlyDressedGames/Unturned-Docs#195]
There's a strange issue with one end of a road twisting and distorting due to ignore terrain, similar to backwards curve nodes but it just twists in place instead of backwards. The severity can carry depending on where it is placed, but also have the issue remain even if placed somewhere entirely different. From what I have gathered it's always from the blue end every single time, even when I place the nodes to flip the road 180 degrees, the blue side is still distorted.

This is the typical twisting:
![image](https://user-images.githubusercontent.com/116485278/197382537-964bd904-ab5d-4749-af93-2c414c424eef.png)
![image](https://user-images.githubusercontent.com/116485278/197382542-ebd50a5b-6405-4e17-8936-46c8df1e6ca7.png)
![image](https://user-images.githubusercontent.com/116485278/197382547-220cbe1f-84ee-4f92-a560-84a87e5cb81d.png)
![image](https://user-images.githubusercontent.com/116485278/197382554-0f1cb2ed-ff23-4a46-8f5b-4ed21593bc5b.png)

Here is one that managed to un-twist by being moved forward, but can still obviously has the distortion:
![image](https://user-images.githubusercontent.com/116485278/197382597-da2427d7-5319-4a02-8d4e-bf551e9c4ea5.png)

**Comment by SDGNelson** [comment]
Thanks for the report! Note the docs repo is not usually checked for this kind of thing. I will investigate to get this fixed for the next update.

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
