### ISSUE TITLE
Some features for "Headquarters" map

### ISSUE THREAD

**Issue by 424xClue** [SmartlyDressedGames/Unturned-Docs#200]
Is there will be a chance to feature:
- Boss Zombies health config
I find a little tricky to fight the bosses if their appearance on map designed not for quest-part or gaining special resources from them
- Zombies spawn option for config file for singleplayer
 Singleplayer zombies don't respawn while player being inside navigation zone. Would be nice to have this feature, since HQ map ,playable as designed only in multiplayer, for now, due this issue

**Comment by MoltonMontro** [comment]
Hey clue,

This should probably be posted on the [3.x Community repository](https://github.com/SmartlyDressedGames/Unturned-3.x-Community) instead.

Congrats on the release of the Headquarters map though. I mentioned it in a blogpost, and I've heard that some people have had quite a bit of fun treating it as a Deathmatch map with zombies.

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
