### ISSUE TITLE
Is U3DS compatible with MacOS (AMD64, not AARCH64)? 

### ISSUE THREAD

**Issue by Lion4K** [SmartlyDressedGames/Unturned-Docs#321]
The wiki doesn't say it isn't and when I tried downloading with SteamCMD it says "Invalid Platform".
Tried asking on Discord, but no one there says anything concrete.
And since the Game itself is compatible with MacOS, I thought i'd ask here, and if not, ask to have a warning included in the wiki.

thanks a lot!

**Comment by Lion4K** [comment]
I see.
Are there plans to have it, or there's gonna be just support for the game?

**Comment by SDGNelson** [comment]
Unfortunately not - hosting support is one of the features that's required a fair bit of ongoing per-platform maintenance, so I expect it'd be a bit of a headache to maintain MacOS dedicated server support, especially as it becomes less developer-friendly. :[

**Comment by Lion4K** [comment]
Yes, I imagine it does.
Especially now that Intel based Macs are pretty much history.
And I don't think there's gonna be an Apple Silicon version, unless the team that makes the phone ports are working on it or something.
But still, probably no Server support.

I ended up installing Windows to my Mac and running the U3DS Windows version.

Opted for Windows because Mac OS has the Boot Camp Assistant, so it's just easier.

But thanks a lot for everything!
