### ISSUE TITLE
Port ? and Workshop Problems

### ISSUE THREAD

**Issue by SkyGaming224** [SmartlyDressedGames/Unturned-Docs#55]
I guess I'm going to start with the easier Problem:

4 workshop item(s) requested
Submitting workshop query for 4 item(s)...
Workshop query yielded 4 result(s)
This server's allowed IP for Workshop downloads: ------ [Deleted the IP for the sake of Privacy]
2430518676 'ZWS - Apache Attack Helicopter Pack v1.2' queued for download
2430518676 'ZWS - Apache Attack Helicopter Pack v1.2' has 1 children
        2387768654 (already queued)
2387768654 'ZWS - Dependencies v1.6' queued for download
2264803170 'ZWS - Abrams MBT Vehicle Pack v1.21' queued for download
2264803170 'ZWS - Abrams MBT Vehicle Pack v1.21' has 1 children
        2387768654 (already queued)
2390830630 'ZWS - Leopard Main Battle Tank Pack v1.1' queued for download
2390830630 'ZWS - Leopard Main Battle Tank Pack v1.1' has 1 children
        2387768654 (already queued)
4 workshop item(s) to download...
Downloading workshop item: 2430518676
Download workshop item 2430518676 failed, result: k_EResultNoMatch
Downloading workshop item: 2387768654
Download workshop item 2387768654 failed, result: k_EResultNoMatch
Downloading workshop item: 2264803170
Download workshop item 2264803170 failed, result: k_EResultNoMatch
Downloading workshop item: 2390830630
Download workshop item 2390830630 failed, result: k_EResultNoMatch

Is there a reason this happens? The Workshop Download Id's is properly set up like with the "Old" Server tool and shouldn't make any issues.

Well then to the Second Problem
When trying to join the Server I get the Error Message: "Failed to find a server."
After looking at other Issues I noticed that it is most likely a Port Issue, but the port is set to 27012 (13/14/15/16 are all forwarded) so that shouldn't be an issue. I also tried 27013 is the port we used with the "old" system and thus shouldn't be a problem.
The Only problem I could make out is that there is a second Server Running with the Game "Space Engineers" at 27016 but that also shouldn't be an issue, the Server also ran while we used the "Old" system and never was a problem.

I also don't get any error messages when starting the Server the way Nelson showed in his Tutorial for the new Tool.

**Comment by SDGNelson** [comment]
What do you mean about "old" vs "new" server? You mention it works with the new one so why use the old?

Steam docs specifically recommend 27015+, so if Space Engineers is probably using 27015-27018ish then it may be worth moving your Unturned server to port 27021-27023.

**Comment by SkyGaming224** [comment]
> What do you mean about "old" vs "new" server? You mention it works with the new one so why use the old?

With "old" I mean the way of Hosting before you added the Steam Tool and made the older way unusable while it is nearly the same the way to start the Server is different, and I never mentioned the Steam Tool working until the other way was made unusable I/we always used that way and had with a Port at 27013 never a problem.

> Steam docs specifically recommend 27015+, so if Space Engineers is probably using 27015-27018ish then it may be worth moving your Unturned server to port 27021-27023.

While Space Engineers should be using 16 and some upwards it is definitely worth trying 21-23, well tomorrow need the Owner to port forward them. 
Oh before I forget it is is an Internet Server, not a Lan Server but that shouldn't make any problems right?  And any ideas what could have caused that Workshop Issue?

**Comment by SDGNelson** [comment]
Not sure about the workshop one, but maybe fixing the connection problems will lead to an explanation for the workshop one.

**Comment by SDGNelson** [comment]
Closing as unrelated to documentation. (#279)
